language: node_js
node_js:
  - "lts/*"
cache: yarn

# https://github.com/Ethan-Arrowood/harperdb-connect/blob/master/.travis.yml
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
