export { getCollection } from "./getCollection";
export { setCollection } from "./setCollection";
export { DELETE } from "./DELETE";
export { DELETES } from "./DELETES";
export { GET } from "./GET";
export { GETS } from "./GETS";
export { POST } from "./POST";
export { PUT } from "./PUT";
export { PATCH } from "./PATCH";
